config/routes.rb
Ob::Application.routes.draw do
  resources :moduledates

  root :to => 'static_pages#main'
  resources :messages
  mount Ckeditor::Engine => '/ckeditor'
  resources :activity_logs
  get       '/activity_log/:znum',  to: 'activity_logs#showlogs'
  resources :ftic_modules_availables , :path => "fticadmin"
  resources :users
  resources :user_modules

   get    '/dashboard/report',   to: 'reports#reportone'
   get    '/dashboard/:type',  to: 'static_pages#dashboard'
   get    '/dashdata/',        to: 'static_pages#dashdata'
   post   '/dashdata/',        to: 'static_pages#dashdata'
   get    '/dashstats/',       to: 'static_pages#dashstats'
   get    '/main',             to: 'static_pages#main'
   get    '/home',             to: 'static_pages#home'
   get    '/unauthorized',     to: 'static_pages#unauthorized'
   get    '/transfer',         to: 'static_pages#transfer'
   get    '/gatewayed_home',   to: 'static_pages#gatewayed_home'
   get    '/login',            to: 'login#login'
   match  '/do_manual_login',  to: 'login#do_manual_login', via: 'post'
   get    '/do_manual_login',  to: 'login#do_manual_login'
   get    '/fticsync/',        to: 'static_pages#fticsync'
   match  '/zipcode/',         to: 'static_pages#calc_distance', via: 'post'
   get    '/zipcode',          to: 'static_pages#calc_distance' 
   get    '/messages/new/:znum',    to: 'messages#new'
   get    '/moduledetail/:id/:znum',    to: 'ftic_modules_availables#moduledetail'
   post   '/save_decline',           to: 'declines#save_decline'
   post   '/save_verify_info',       to: 'verify#save_verify_info'
   post   '/save_communication',     to: 'communications#save_communication'
   post   '/save_lc',                to: 'communities#save_lc'
   post   'update_ftic_verify_module',  to: 'ftic_modules_availables#update_ftic_verify_module'
   get    'update_ftic_verify_module',  to: 'ftic_modules_availables#update_ftic_verify_module'
   post   'update_ftic_account_module',  to: 'ftic_modules_availables#update_ftic_account_module'
   post   'update_ftic_deposit_module',  to: 'ftic_modules_availables#update_ftic_deposit_module'
   post   'update_ftic_communication_module',  to: 'ftic_modules_availables#update_ftic_communication_module'
   post   'update_ftic_immunization_module',  to: 'ftic_modules_availables#update_ftic_immunization_module'
   get    'update_ftic_immunization_module',  to: 'ftic_modules_availables#update_ftic_immunization_module'
   post   'update_ftic_residency_module',  to: 'ftic_modules_availables#update_ftic_residency_module'
   post   'update_ftic_finaid_module',  to: 'ftic_modules_availables#update_ftic_finaid_module'
   post   'update_ftic_finaidalt_module',  to: 'ftic_modules_availables#update_ftic_finaidalt_module'
   post   'update_ftic_housing_module',  to: 'ftic_modules_availables#update_ftic_housing_module'
   post   'update_ftic_aleks_module',  to: 'ftic_modules_availables#update_ftic_aleks_module'
   post   'update_ftic_orientation_module',  to: 'ftic_modules_availables#update_ftic_orientation_module'
   get    'update_ftic_orientation_module',  to: 'ftic_modules_availables#update_ftic_orientation_module'
   post   'update_ftic_learning_module',  to: 'ftic_modules_availables#update_ftic_learning_module'
   get    'update_ftic_learning_module',  to: 'ftic_modules_availables#update_ftic_learning_module'
   post   'update_ftic_oars_module',  to: 'ftic_modules_availables#update_ftic_oars_module'
   post   'update_ftic_reg_module',  to: 'ftic_modules_availables#update_ftic_reg_module'
   post   'update_ftic_tuition_module',  to: 'ftic_modules_availables#update_ftic_tuition_module'
   post   'update_ftic_emergency_module',  to: 'ftic_modules_availables#update_ftic_emergency_module'
   post   'update_ftic_alert_module',  to: 'ftic_modules_availables#update_ftic_alert_module'
   post   'update_ftic_owlcard_module',  to: 'ftic_modules_availables#update_ftic_owlcard_module'   
   post   'update_ftic_book_module',  to: 'ftic_modules_availables#update_ftic_book_module'   
   post   'update_ftic_vehicle_module',  to: 'ftic_modules_availables#update_ftic_vehicle_module'   
   match '*a', :to => 'static_pages#routing_error'
end

app/models/moduledate.rb
class Moduledate < ActiveRecord::Base
  attr_accessible :closedate, :name, :opendate, :termvalue
end

app/controllers/moduledates_controller.rb
class ModuledatesController < ApplicationController
  # GET /moduledates
  # GET /moduledates.json

  before_filter :authenticate_for_admin
  def index
    @moduledates = Moduledate.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @moduledates }
    end
  end

  # GET /moduledates/1
  # GET /moduledates/1.json
  def show
    @moduledate = Moduledate.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @moduledate }
    end
  end

  # GET /moduledates/new
  # GET /moduledates/new.json
  def new
    @moduledate = Moduledate.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @moduledate }
    end
  end

  # GET /moduledates/1/edit
  def edit
    @moduledate = Moduledate.find(params[:id])
    @termval =  @moduledate.termvalue
  end

  # POST /moduledates
  # POST /moduledates.json
  def create
    @moduledate = Moduledate.new(moduledate_params)   
    respond_to do |format|
      if @moduledate.save
        format.html { redirect_to @moduledate, notice: 'Moduledate was successfully created.' }
        format.json { render json: @moduledate, status: :created, location: @moduledate }
      else
        format.html { render action: "new" }
        format.json { render json: @moduledate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /moduledates/1
  # PATCH/PUT /moduledates/1.json
  def update
    @moduledate = Moduledate.find(params[:id])

    respond_to do |format|
      if @moduledate.update_attributes(moduledate_params)
        format.html { redirect_to @moduledate, notice: 'Moduledate was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @moduledate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /moduledates/1
  # DELETE /moduledates/1.json
  def destroy
    @moduledate = Moduledate.find(params[:id])
    @moduledate.destroy

    respond_to do |format|
      format.html { redirect_to moduledates_url }
      format.json { head :no_content }
    end
  end

  
   protected

   def authenticate_for_admin
      user = User.where(:netid => session[:cas_user])
      if user.count == 0 #no info found
       redirect_to unauthorized_path
      end       
   end 


  private

    # Use this method to whitelist the permissible parameters. Example:
    # params.require(:person).permit(:name, :age)
    # Also, you can specialize this method with per-user checking of permissible attributes.
    def moduledate_params
      params.require(:moduledate).permit(:closedate, :name, :opendate, :termvalue)
    end
end

app/helpers/moduledates_helper.rb
module ModuledatesHelper
end

app/views/moduledates/_form.html.erb
 <div class="row">
    &nbsp;
   </div>
  <div class="container">
    <div class="row">
      <article class="col-sm-12 col-md-12 content">
    <div class="my-account margin-top">
      
      <div class="row">
        <div class="col-sm-12 col-md-12">
        <div class="title-box">
          <h2 class="title">New Module Date</h2>
        </div>

<%= form_for(@moduledate) do |f| %>
  <% if @moduledate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@moduledate.errors.count, "error") %> prohibited this moduledate from being saved:</h2>

      <ul>
      <% @moduledate.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "" %><br />
    <%= f.text_area :name, :class => 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :opendate, "open date" %><br />
    <%= f.date_select :opendate,{},{:class => 'form-control'} %>
  </div>
  <div class="field">
    <%= f.label :closedate, "close date" %><br />
    <%= f.date_select :closedate, {} ,{:class => 'form-control'} %>
  </div>
  <div class="field">
    <%= f.label :termname, "term" %><br />
    <%= f.select(:termvalue, options_for_select([["Select One", ""],["Fall 2016", "201608"],["Summer 2016","201605"],["Spring 2017","201701"],["Fall 2017","201708"]], @termval ), {} ,{:class => 'form-control'}) %>
  </div>
  <div class="actions">
    <%= f.submit "save", :class => 'btn btn-danger' %>
  </div>
<% end %>
</div>        
      </div>     
    </div>
      </article><!-- .content -->
     </div>
  </div>

app/views/moduledates/edit.html.erb
<h1>Edit module open/close date</h1>

<%= render 'form' %>

<%= link_to 'Show', @moduledate %> |
<%= link_to 'Back', moduledates_path %>

app/views/moduledates/index.html.erb
<h1>Module open/close dates</h1>

<table id="datetable" class="table table-striped table-bordered table-hover">
  <thead>
  <tr>
    <th>Module</th>
    <th>Open</th>
    <th>Close</th>
    <th>Term</th>
    <th>Actions</th>   
  </tr>
</thead>
<% @moduledates.each do |moduledate| %>
  <tr>
    <td><%= moduledate.name %></td>
    <td><%= moduledate.opendate %></td>
    <td><%= moduledate.closedate %></td>
    <td><%= moduledate.termvalue %></td>
    <td colspan="3"><%= link_to 'Show', moduledate %>
    <%= link_to 'Edit', edit_moduledate_path(moduledate) %>
    <%= link_to 'Destroy', moduledate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Module Date', new_moduledate_path, {:class => 'btn btn-info'}  %>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script type="text/javascript" language="javascript" src="//cdn.datatables.net/1.10.7/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" language="javascript" src="//cdn.datatables.net/plug-ins/1.10.7/integration/bootstrap/3/dataTables.bootstrap.js"></script> 

<script type="text/javascript">
$(document).ready(function(){
 $('#datetable').dataTable();
});
</script>

app/views/moduledates/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', moduledates_path %>

app/views/moduledates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @moduledate.name %>
</p>

<p>
  <b>Opendate:</b>
  <%= @moduledate.opendate %>
</p>

<p>
  <b>Closedate:</b>
  <%= @moduledate.closedate %>
</p>


<%= link_to 'Edit', edit_moduledate_path(@moduledate), {:class => 'btn btn-info'}  %> |
<%= link_to 'Back', moduledates_path, {:class => 'btn btn-info'}  %>