config/routes.rb
Ob::Application.routes.draw do
  resources :moduledates

  root :to => 'static_pages#main'
  resources :messages
  mount Ckeditor::Engine => '/ckeditor'
  resources :activity_logs
  get       '/activity_log/:znum',  to: 'activity_logs#showlogs'
  resources :ftic_modules_availables , :path => "fticadmin"
  resources :users
  resources :user_modules

   get    '/dashboard/report',   to: 'reports#reportone'
   get    '/dashboard/:type',  to: 'static_pages#dashboard'
   get    '/dashdata/',        to: 'static_pages#dashdata'
   post   '/dashdata/',        to: 'static_pages#dashdata'
   get    '/dashstats/',       to: 'static_pages#dashstats'
   get    '/main',             to: 'static_pages#main'
   get    '/home',             to: 'static_pages#home'
   get    '/unauthorized',     to: 'static_pages#unauthorized'
   get    '/transfer',         to: 'static_pages#transfer'
   get    '/gatewayed_home',   to: 'static_pages#gatewayed_home'
   get    '/login',            to: 'login#login'
   match  '/do_manual_login',  to: 'login#do_manual_login', via: 'post'
   get    '/do_manual_login',  to: 'login#do_manual_login'
   get    '/fticsync/',        to: 'static_pages#fticsync'
   match  '/zipcode/',         to: 'static_pages#calc_distance', via: 'post'
   get    '/zipcode',          to: 'static_pages#calc_distance' 
   get    '/messages/new/:znum',    to: 'messages#new'
   get    '/moduledetail/:id/:znum',    to: 'ftic_modules_availables#moduledetail'
   post   '/save_decline',           to: 'declines#save_decline'
   post   '/save_verify_info',       to: 'verify#save_verify_info'
   post   '/save_communication',     to: 'communications#save_communication'
   post   '/save_lc',                to: 'communities#save_lc'
   post   'update_ftic_verify_module',  to: 'ftic_modules_availables#update_ftic_verify_module'
   get    'update_ftic_verify_module',  to: 'ftic_modules_availables#update_ftic_verify_module'
   post   'update_ftic_account_module',  to: 'ftic_modules_availables#update_ftic_account_module'
   post   'update_ftic_deposit_module',  to: 'ftic_modules_availables#update_ftic_deposit_module'
   post   'update_ftic_communication_module',  to: 'ftic_modules_availables#update_ftic_communication_module'
   post   'update_ftic_immunization_module',  to: 'ftic_modules_availables#update_ftic_immunization_module'
   get    'update_ftic_immunization_module',  to: 'ftic_modules_availables#update_ftic_immunization_module'
   post   'update_ftic_residency_module',  to: 'ftic_modules_availables#update_ftic_residency_module'
   post   'update_ftic_finaid_module',  to: 'ftic_modules_availables#update_ftic_finaid_module'
   post   'update_ftic_finaidalt_module',  to: 'ftic_modules_availables#update_ftic_finaidalt_module'
   post   'update_ftic_housing_module',  to: 'ftic_modules_availables#update_ftic_housing_module'
   post   'update_ftic_aleks_module',  to: 'ftic_modules_availables#update_ftic_aleks_module'
   post   'update_ftic_orientation_module',  to: 'ftic_modules_availables#update_ftic_orientation_module'
   get    'update_ftic_orientation_module',  to: 'ftic_modules_availables#update_ftic_orientation_module'
   post   'update_ftic_learning_module',  to: 'ftic_modules_availables#update_ftic_learning_module'
   get    'update_ftic_learning_module',  to: 'ftic_modules_availables#update_ftic_learning_module'
   post   'update_ftic_oars_module',  to: 'ftic_modules_availables#update_ftic_oars_module'
   post   'update_ftic_reg_module',  to: 'ftic_modules_availables#update_ftic_reg_module'
   post   'update_ftic_tuition_module',  to: 'ftic_modules_availables#update_ftic_tuition_module'
   post   'update_ftic_emergency_module',  to: 'ftic_modules_availables#update_ftic_emergency_module'
   post   'update_ftic_alert_module',  to: 'ftic_modules_availables#update_ftic_alert_module'
   post   'update_ftic_owlcard_module',  to: 'ftic_modules_availables#update_ftic_owlcard_module'   
   post   'update_ftic_book_module',  to: 'ftic_modules_availables#update_ftic_book_module'   
   post   'update_ftic_vehicle_module',  to: 'ftic_modules_availables#update_ftic_vehicle_module'   
   match '*a', :to => 'static_pages#routing_error'
end

app/models/user_module.rb
class UserModule < ActiveRecord::Base
  attr_accessible :module, :module_id, :netid, :userid
  belongs_to :user
  belongs_to :module
end

app/controllers/user_modules_controller.rb
class UserModulesController < ApplicationController
  # GET /user_modules
  # GET /user_modules.json
  def index
    @user_modules = UserModule.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @user_modules }
    end
  end

  # GET /user_modules/1
  # GET /user_modules/1.json
  def show
    @user_module = UserModule.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user_module }
    end
  end

  # GET /user_modules/new
  # GET /user_modules/new.json
  def new
    @user_module = UserModule.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user_module }
    end
  end

  # GET /user_modules/1/edit
  def edit
    @user_module = UserModule.find(params[:id])
  end

  # POST /user_modules
  # POST /user_modules.json
  def create
    @user_module = UserModule.new(user_module_params)

    respond_to do |format|
      if @user_module.save
        format.html { redirect_to @user_module, notice: 'User module was successfully created.' }
        format.json { render json: @user_module, status: :created, location: @user_module }
      else
        format.html { render action: "new" }
        format.json { render json: @user_module.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_modules/1
  # PATCH/PUT /user_modules/1.json
  def update
    @user_module = UserModule.find(params[:id])

    respond_to do |format|
      if @user_module.update_attributes(user_module_params)
        format.html { redirect_to @user_module, notice: 'User module was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user_module.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_modules/1
  # DELETE /user_modules/1.json
  def destroy
    @user_module = UserModule.find(params[:id])
    @user_module.destroy

    respond_to do |format|
      format.html { redirect_to user_modules_url }
      format.json { head :no_content }
    end
  end

  private

    # Use this method to whitelist the permissible parameters. Example:
    # params.require(:person).permit(:name, :age)
    # Also, you can specialize this method with per-user checking of permissible attributes.
    def user_module_params
      params.require(:user_module).permit(:module, :module_id, :netid, :userid)
    end
end

app/helpers/user_modules_helper.rb
module UserModulesHelper
end

app/views/user_modules/_form.html.erb
<%= form_for(@user_module) do |f| %>
  <% if @user_module.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_module.errors.count, "error") %> prohibited this user_module from being saved:</h2>

      <ul>
      <% @user_module.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :netid %><br />
    <%= f.text_field :netid %>
  </div>
  <div class="field">
    <%= f.label :userid %><br />
    <%= f.number_field :userid %>
  </div>
  <div class="field">
    <%= f.label :module %><br />
    <%= f.text_field :module %>
  </div>
  <div class="field">
    <%= f.label :module_id %><br />
    <%= f.number_field :module_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_modules/edit.html.erb
<h1>Editing user_module</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_module %> |
<%= link_to 'Back', user_modules_path %>

app/views/user_modules/index.html.erb
<h1>Listing user_modules</h1>

<table>
  <tr>
    <th>Netid</th>
    <th>Userid</th>
    <th>Module</th>
    <th>Module</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @user_modules.each do |user_module| %>
  <tr>
    <td><%= user_module.netid %></td>
    <td><%= user_module.userid %></td>
    <td><%= user_module.module %></td>
    <td><%= user_module.module_id %></td>
    <td><%= link_to 'Show', user_module %></td>
    <td><%= link_to 'Edit', edit_user_module_path(user_module) %></td>
    <td><%= link_to 'Destroy', user_module, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User module', new_user_module_path %>

app/views/user_modules/new.html.erb
<h1>New user_module</h1>

<%= render 'form' %>

<%= link_to 'Back', user_modules_path %>

app/views/user_modules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Netid:</b>
  <%= @user_module.netid %>
</p>

<p>
  <b>Userid:</b>
  <%= @user_module.userid %>
</p>

<p>
  <b>Module:</b>
  <%= @user_module.module %>
</p>

<p>
  <b>Module:</b>
  <%= @user_module.module_id %>
</p>


<%= link_to 'Edit', edit_user_module_path(@user_module) %> |
<%= link_to 'Back', user_modules_path %>